src/apps/workflow/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (OrderListView, OrderCreateView, OrderUpdateView, OrderDetailView,
                    NoteListView, ModelListView, ModelUpdateView, add_model, start_job,
                    start_second_stage, cancel_job, switch_job, add_note, add_delivery_job)


app_name = 'workflow'


urlpatterns = [
    path('', TemplateView.as_view(template_name='main/home.html'), name='home'),

    path('orders/', OrderListView.as_view(), name='orders-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<slug:slug>/', OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>/update', OrderUpdateView.as_view(), name='order-update'),
    path('orders/add', OrderCreateView.as_view(), name='order-add'),

    path('orders/<int:pk>/notes', NoteListView.as_view(), name='order-notes'),
    path('orders/<int:order_id>/notes/add', add_note, name='note-create'),

    path('orders/start_job/<int:order_id>', start_job, name='start-job'),
    path('orders/cancel_job/<int:order_id>', cancel_job, name='cancel-job'),
    path('orders/start_second_stage/<int:order_id>', start_second_stage, name='start-second-stage'),
    path('orders/switch_job/<int:order_id>/<slug:slug>/<int:stage_id>', switch_job, name='switch-job'),
    path('orders/add_delivery_job/<int:order_id>', add_delivery_job, name='add-delivery-job'),


    path('models/', ModelListView.as_view(), name='models'),
    path('models/add', add_model, name='model-add'),
    path('models/<int:pk>/update', ModelUpdateView.as_view(), name='model-update'),
]

src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('tinymce/', include('tinymce.urls')),

    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('accounts/password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             success_url='/login/'
         ),
         name='password_reset'),
    path('accounte/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    path('', include('workflow.urls', namespace='workflow'), name='home'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/apps/workflow/models/base.py
from django.db import models


class BaseModel(models.Model):

    id = models.AutoField(primary_key=True)

    class Meta:
        abstract = True



class Nameable(models.Model):

    name = models.CharField(max_length=100)

    class Meta:
        abstract = True



class Creatable(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True



class Updatable(models.Model):

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

src/apps/workflow/models/stage.py
from django.db import models

from .base import BaseModel, Nameable

class WfStageList(BaseModel, Nameable):

    DEFAULT_STAGE_ID = 2

    class Meta:
        managed = False
        db_table = 'wf_stage_list'


    def __str__(self):
        return self.name



class WfWorkStageList(BaseModel, Nameable):

    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(unique=True)

    DEFAULT_STAGE_ID = 1

    class Meta:
        managed = False
        db_table = 'wf_work_stage_list'

        verbose_name = 'Стадію виконання роботи'
        verbose_name_plural = 'Стадії виконання роботи'


    def __str__(self):
        return self.name



class OrderStatusList(BaseModel, Nameable):

    DEFAULT_STATUS_ID = 1

    class Meta:
        managed = False
        db_table = 'wf_order_status_list'

        verbose_name = 'Статус замовлення'
        verbose_name_plural = 'Статуси замовлень'


    def __str__(self):
        return self.name

src/apps/workflow/views.py
import json

from django.db.models import Q, OuterRef, Subquery, Value, Max, F, Count, Prefetch, Case, When, Exists, BooleanField
from django.db.models.lookups import GreaterThan
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from django.views.decorators.http import require_http_methods
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, Http404
from django.core.exceptions import ObjectDoesNotExist

from .models.core import Order, OrderStatus, OrderWorkStage, WorkLog, Note, WfModelList, WfWorkStageList
from .models.stage import WfStageList, OrderStatusList
from .filters import OrderFilter, NoteFilter
from .forms import OrderForm, NoteLogForm, ModelForm
from .mixins import FilteredListViewMixin
from .pagination import CustomPagination
from .queries import get_max_work_stages, get_current_stage
from .utils import annotate_current_stage, annotate_notes


class OrderListView(LoginRequiredMixin, FilteredListViewMixin):

    http_method_names = ['get', 'head', 'options', 'trace',]

    queryset = Order.objects.all()
    ordering = ['-id',]
    paginate_by = 50
    paginator_class = CustomPagination
    filterset_class = OrderFilter

    context_object_name = 'orders'
    template_name = 'workflow/order/list.html'


    def get_queryset(self):
        queryset = super().get_queryset()

        principal_groups = self.kwargs.get('principal_groups', [])

        select_related = [
            'model',
            'configuration',
            'fireclay_type',
            'glazing_type',
            'handle_type',
            'frame_type',
            'priority',
        ]

        prefetch_related = []

        work_stages = get_max_work_stages()

        queryset = queryset.annotate(**annotate_current_stage(work_stages))

        if any(x in ['manager', 'lead', ] for x in principal_groups):
            select_related += ['payment']

            ready_for_second_stage = OrderWorkStage.objects.raw(
                '''
                    SELECT wol.id FROM wf_order_log wol
                    WHERE wol.start_manufacturing_semi_finished  = 0 AND
                    wol.id IN (
                        SELECT wows.order_id FROM wf_order_work_stage wows
                        INNER JOIN wf_work_log wwl
                        ON wows.id = wwl.order_work_stage_id
                        WHERE wows.work_stage_id <= 6
                        AND wows.order_id IN (
                            SELECT wows.order_id  FROM wf_order_work_stage wows
                            INNER JOIN wf_work_log wwl
                            ON wows.id = wwl.order_work_stage_id
                            WHERE wows.work_stage_id > 6
                            GROUP BY wows.order_id
                            HAVING COUNT(DISTINCT wows.id) = SUM(CASE WHEN wwl.stage_id = 1 THEN 0 ELSE 1 END)
                        )
                        GROUP BY wows.order_id
                        HAVING COUNT(DISTINCT wows.id) = SUM(CASE WHEN wwl.stage_id = 1 THEN 1 ELSE 0 END)
                    );
                '''
            )

            orders_ = Order.objects.filter(Q(id__in=OuterRef('id')) & Q(id__in=[id.id for id in ready_for_second_stage])) \
                                   .annotate(ready_for_second_stage=Value(True))

            max_status_ = OrderStatus.objects.values('order').annotate(max_id=Max('id'))
            is_ready = OrderStatus.objects.filter(
                id__in=Subquery(max_status_.values('max_id')),
                order=OuterRef('id'),
                status=2
            )
            is_not_cancellable = OrderStatus.objects.filter(
                id__in=Subquery(max_status_.values('max_id')),
                order=OuterRef('id'),
                status_id__in=[3, 4]
            )

            work_log_ = WorkLog.objects.values('work_stage__order').annotate(max_id=Max('id'))
            work_log = WorkLog.objects.filter(
                Q(work_stage__order=OuterRef('id')) &
                Q(id__in=Subquery(work_log_.values('max_id'))),
            )

            queryset = queryset.annotate(
                notes_count=Count('notes', distinct=True),
                ready_for_second_stage=Subquery(orders_.values('ready_for_second_stage')),
                ready_for_delivery=Case(
                        When(
                            Exists(is_ready) & ~Exists(OrderWorkStage.objects.filter(Q(order=OuterRef('id')) & Q(stage__id=12))),
                            then=Value(True)
                            ),
                        default=Value(False),
                        output_field=BooleanField()
                    ),
                is_cancellable=Case(
                        When(
                            Exists(is_not_cancellable),
                            then=Value(False)
                            ),
                        default=Value(True),
                        output_field=BooleanField()
                ),
                stage_status=Subquery(work_log.values('stage')),
            )

        else:
            slug = self.kwargs.get('slug', None)
            listing = self.request.GET.get('listing', 'in_progress')

            try:
                stage = WfWorkStageList.objects.get(slug=slug)
            except ObjectDoesNotExist:
                raise Http404

            prefetch_related += ['notes',]

            # work_log_ = WorkLog.objects.raw(
            #     '''
            #         SELECT wwl.id
            #         FROM wf_work_log wwl
            #         INNER JOIN  (
            #             SELECT MAX(wwl_.id) AS max_id
            #             FROM wf_work_log wwl_
            #             INNER JOIN wf_order_work_stage wows_ ON wwl_.order_work_stage_id = wows_.id
            #             WHERE wows_.work_stage_id = %s
            #             GROUP BY wwl_.order_work_stage_id
            #         ) temp_
            #         ON temp_.max_id = wwl.id;
            #     ''', [stage.id]
            # )

            # work_log = WorkLog.objects.filter(
            #     Q(work_stage__order=OuterRef('id')) &
            #     Q(id__in=[id.id for id in work_log_])
            # )

            work_log_ = WorkLog.objects.values('work_stage').filter(
                            Q(work_stage__stage=stage)
                        ).annotate(max_id=Max('id'))

            work_log = WorkLog.objects.filter(
                Q(work_stage__order=OuterRef('id')) &
                Q(id__in=Subquery(work_log_.values('max_id')))
            )

            work_stage_last = OrderWorkStage.objects.values('order').filter(
                Q(order_of_execution__in=Subquery(
                    OrderWorkStage.objects.filter(Q(order=OuterRef('order')) & Q(stage=stage) & Q(is_locked=False)).values('order_of_execution')) - 1
                  ) &
                Q(order=OuterRef('id')) &
                Q(logs__stage__isnull=False)
            ).annotate(last_date=Max('logs__created_at'))


            max_status_ = OrderStatus.objects.values('order').annotate(max_id=Max('id'))
            is_delivered_or_cancelled = OrderStatus.objects.filter(Q(id__in=max_status_.values('max_id')) & Q(order__id=OuterRef('id')) & Q(status__in=[3, 4]))

            listing_filter = Q()
            if listing == 'in_progress' and 'employee' in principal_groups:
                listing_filter = (
                    # Q(order_stages__logs__in=Subquery(work_log_.values('max_id'))) &
                    ~Q(order_stages__logs__stage__id=1)
                )


            queryset = queryset.filter(
                                    Q(order_stages__stage=stage) &
                                    Q(order_stages__is_locked=False) &
                                    Q(start_manufacturing_semi_finished=Case(
                                            When(order_stages__stage__gt=6, then=True),
                                            default=F('start_manufacturing_semi_finished')
                                        )
                                    ) &
                                    Q(listing_filter) &
                                    ~Q(statuses__in=Subquery(is_delivered_or_cancelled.values('id')))
                                ) \
                                .annotate(
                                    notes_count=Count('notes', distinct=True),
                                    username=work_log.values('user__username'),
                                    stage_id=work_log.values('stage__id'),
                                    work_completed_date=Case(
                                        When(GreaterThan(F('order_stages__order_of_execution'), 0),
                                        then=Subquery(work_stage_last.values('last_date'))),
                                        default=F('start_date')
                                    )
                                )

        queryset = queryset.select_related(*select_related).prefetch_related(*prefetch_related)

        return queryset


    def get_template_names(self):
        template = super().get_template_names()
        is_partial = self.request.headers.get('HX-Trigger', None) == 'paginator'

        principal_groups = self.kwargs.get('principal_groups', [])
        work_groups = self.kwargs.get('work_groups', [])

        template_map = {
            'dxf_version_control': 'workflow/dxf_log',
            'cut': 'workflow/cut_log',
            'bend': 'workflow/bend_log',
            'weld': 'workflow/weld_log',
            'locksmith': 'workflow/locksmith_log',
            'locksmith_door': 'workflow/locksmith_log',
            'paint': 'workflow/paint_log',
            'fireclay': 'workflow/fireclay_log',
            'glass': 'workflow/glass_log',

src/apps/workflow/templates/workflow/manager_log/list.html
{% extends "base.html" %}
{% load tags %}
{% load slippers %}


{% block breadcrumb %}
    <li>
        <a href="{% url 'workflow:home' %}" class="">
            <span class="flex items-center mdi p-0.5 md:p-1 mdi-chevron-right text-gray-700 hover:text-gray-900">
                <span class="ml-2">Головна</span>
            </span>
        </a>
    </li>
{% endblock %}

{% block content %}

  <div class="flex justify-end mr-10">
      <div class="flex flex-row pr-2">
        <div class="mr-2">

          <div onclick="openFilterPanel()">
            {% #primary-button %}
              <span>Фільтри</span>
              <span class="ml-2 mdi mdi-filter-variant"></span>
            {% /primary-button %}
          </div>
        </div>

        <div class="relative">
          {% #dropdown label="Додати" %}
            <a class="text-sm
                      py-2
                      px-4
                      font-normal
                      block
                      w-full
                      whitespace-nowrap
                      bg-transparent
                      text-gray-700
                      hover:bg-gray-200"
               href="{% url 'workflow:order-add' %}">
              Замовлення
            </a>
            <a class="text-sm
                      py-2
                      px-4
                      font-normal
                      block
                      w-full
                      whitespace-nowrap
                      bg-transparent
                      text-gray-700
                      hover:bg-gray-200"
               href="{% url 'admin:index' %}">
              Нові моделі
            </a>
          {% /dropdown %}
        </div>
      </div>
    </div>

    <div id="order-wrapper" hx-swap-oob="true" class="mx-2">

      <aside class="w-auto h-auto z-10 top-18 fixed"
             aria-label="Sidebar"
             id="filter-panel"
             style="display: {% if not 'isOpenFilterPanel' in request.COOKIES or request.COOKIES.isOpenFilterPanel == 'true' %} flex {% else %} none {% endif %};">
        <div class="py-4 px-2 bg-gray-50 rounded-sm shadow-md">
          <div class="flex justify-end">
            <span class="mdi mdi-close mr-2 text-xs md:text-base hover:text-black hover:bg-gray-200 rounded-lg p-1.5 cursor-pointer" onclick="closeFilterPanel()"></span>
          </div>
          <h2 class="text-base md:text-xl font-medium text-center border-b pb-2">Фільтрувати замовлення <span class="ml-2 mdi mdi-filter-variant"></span></h2>
          <form hx-get="{% url 'workflow:orders-list' %}"
                hx-target="#order-list"
                hx-swap="innerHTML"
                hx-push-url="true"
                hx-indicator=".progress">
            <div class="grid grid-cols-5 gap-0.5 md:gap-1 space-x-2 mx-auto mt-8 mb-2 text-xs md:text-sm justify-center">
              {% for filter in filterset.form %}
                {{ filter.errors }}
                  <div class="col-span-2 font-normal justify-self-center">{{ filter.label }}</div>
                  <div class="col-span-3">
                    {{ filter }}
                  </div>
                  {% if filter.help_text %}
                    <p class="help">{{ filter.help_text|safe }}</p>
                  {% endif %}
              {% endfor %}
            </div>

            <div class="flex justify-end mr-10 border-t pt-2 space-x-2">
              {% url 'workflow:orders-list' as link %}
              {% #primary-button variant="gray" hx_get=link hx_target="#order-wrapper" hx_indicator=".progress" %}
                <span>Скинути</span>
              {% /primary-button %}
              {% #primary-button type="submit" %}
                <span>Застосувати</span>
              {% /primary-button %}
            </div>
          </form>
        </div>
      </aside>

      <main class="relative max-h-[80vh] overflow-x-auto overflow-y-auto shadow-md rounded-sm mt-2 mx-2 md:mx-10" id="order-list" hx-swap-oob="true">

          <table class="w-full text-sm text-left drop-shadow-lg py-4 px-4 bg-white shadow-lg">
              <thead class="text-xs sticky top-0 md:text-sm text-gray-800 uppercase bg-gray-200 text-center">
                  <tr>
                      <th scope="col" class="px-3 py-1 md:py-2">Замовлення</th>
                      <th scope="col" class="px-3 py-1 md:py-2">Пріоритет</th>
                      <th scope="col" class="px-3 py-1 md:py-2">Статус</span></th>
                      <th scope="col" class="px-3 py-1 md:py-2">Модель</th>
                      <th scope="col" class="px-3 py-1 md:py-2">Конфігурація</th>
                      <th scope="col" class="px-3 py-1 md:py-2">Ціна</th>
                      <th scope="col" class="px-3 py-1 md:py-2">Оплата</th>
                      <th scope="col" class="px-3 py-1 md:py-2">Дата початку</th>
                      <th scope="col" class="px-3 py-1 md:py-2 w-10">Доставка</th>
                      <th scope="col" class="px-3 py-1 md:py-2">
                          <span class="sr-only">Actions</span>
                      </th>
                  </tr>
              </thead>
              <tbody id="paginated-table">
                {% include 'workflow/manager_log/partial.html' %}
              </tbody>
          </table>
      </main>

      <!-- <div id="page-loading" class="progress mt-2" style="display: none;">
        <div class="h-10 w-full flex justify-center items-center">
          <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-blue-700" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
        </div>
      </div> -->

      <!-- {% if is_paginated %}
        {% include 'components/pagination.html' %}
      {% endif %} -->
    </div>

{% endblock %}

src/apps/workflow/templates/workflow/manager_log/order.html
<tr id="order_{{ order.id }}"
    class="bg-stone-50 hover:bg-stone-100 border-b font-light text-xs md:text-sm text-center h-12 md:h-10">
    <th scope="row" class="px-3 font-medium text-blue-700 whitespace-nowrap">
      <div class="flex items-center justify-center">
        <div class="h-1.5 w-1.5 sm:h-2 sm:w-2 rounded-full bg-{% if order.stage_status == 1 %}green-500{% elif order.stage_status == 2 %}orange-500{% else %}gray-500{% endif %} ml-2 mr-3"></div>
        <a href="{% url 'workflow:order-detail' order.id %}"
           class="text-xs md:text-sm lg:text-md">
           {{ order.id }} <span class="mdi mdi-link-variant"></span>
        </a>
      </div>
    </th>
    <td>
        <span>
            {% if order.priority.id == 1 %}
                <span class="mdi mdi-star text-green-900"></span>
            {% elif order.priority.id == 2 %}
                <span class="mdi mdi-star text-yellow-600"></span>
                <span class="mdi mdi-star text-yellow-600"></span>
            {% else %}
                <span class="mdi mdi-star text-yellow-900"></span>
                <span class="mdi mdi-star text-yellow-900"></span>
                <span class="mdi mdi-star text-yellow-900"></span>
            {% endif %}
        </span>
    </td>
    <td>
        <span>{{ order.current_stage }}</span>
    </td>
    <td>
        <span class="">{{ order.model }}</span>
    </td>
    <td>
        <span class="">{{ order.configuration }}</span>
    </td>
    <td>{{ order.price|default:"" }}</td>
    <td>
        {% if order.payment.id == 1 %}
            <span class="mdi text-lg p-0.5 md:p-1 mdi-check-circle-outline text-green-700"></span>
        {% elif order.payment.id == 2 %}
            <span class="mdi text-lg p-0.5 md:p-1 mdi-close-circle-outline text-red-700"></span>
        {% else %}
            <span class="mdi text-lg p-0.5 md:p-1 mdi-alarm text-blue-700"></span>
        {% endif %}
    </td>
    <td>
      <span class="">{{ order.start_date|default:"" }}</span>
    </td>
    <td>
        <span class="">{{ order.delivery|default:"" }}</span>
    </td>
    <td>
        <div class="px-2 flex flex-row space-x-2 items-center">
            {% if order.ready_for_delivery %}
                <button hx-target="#order_{{ order.id }}"
                        hx-post="{% url 'workflow:add-delivery-job' order_id=order%}"
                        hx-swap="outerHTML"
                        hx-confirm="Віддати на відправлення?"
                        role="button">
                    <span class="mdi text-lg p-0.5 md:p-1 mdi-truck-delivery text-blue-700 rounded hover:bg-sky-200"></span>
                </button>
            {% endif %}

            {% if not order.start_manufacturing %}
                <button hx-target="#order_{{ order.id }}"
                        hx-post="{% url 'workflow:start-job' order_id=order%}"
                        hx-swap="outerHTML"
                        hx-confirm="Подати в роботу?"
                        role="button">
                    <span class="mdi text-lg p-0.5 md:p-1 mdi-airplane-takeoff text-blue-700 rounded hover:bg-sky-200"></span>
                </button>
            {% endif %}

            {% if not order.start_manufacturing_semi_finished and order.ready_for_second_stage %}
                <button hx-target="#order_{{ order.id }}"
                        hx-post="{% url 'workflow:start-second-stage' order_id=order%}"
                        hx-swap="outerHTML"
                        hx-confirm="Подати напівфабрикат в роботу?"
                        role="button">
                    <span class="flex items-center mdi text-lg p-0.5 mdi-airplane-takeoff text-blue-700 rounded hover:bg-sky-200">
                        <span class="ml-0.5 text-xs font-bold">2</span>
                    </span>
                </button>
            {% endif %}

            <a href="{% url 'workflow:order-notes' order.id %}" class="text-xs md:text-sm lg:text-md">
                <span class="flex flex-row rounded hover:bg-sky-200 mdi text-lg p-0.5 md:p-1 mdi-message-bulleted text-blue-700">
                  <span class="ml-0.5 text-xs font-semibold">{{ order.notes_count }}</span>
                </span>
            </a>

            <a href="{% url 'workflow:order-update' order.id %}" class="text-xs md:text-sm lg:text-md">
                <span class="mdi text-lg p-0.5 md:p-1 mdi-pencil-outline text-blue-700 rounded hover:bg-sky-200">
                </span>
            </a>

            {% if order.is_cancellable and perms.workflow.delete_logentry %}
              <button hx-target="#order_{{ order.id }}"
                      hx-delete="{% url 'workflow:cancel-job' order_id=order%}"
                      hx-swap="outerHTML"
                      hx-indicator=".progress"
                      hx-confirm="Скасувати замовлення?"
                      role="button">
                  <span class="mdi text-lg p-0.5 md:p-1 mdi-close-circle text-red-700 rounded hover:bg-sky-200"></span>
              </button>
            {% endif %}
        </div>
    </td>
</tr>

src/apps/workflow/templates/workflow/manager_log/partial.html
{% load tags %}

{% for order in orders %}
    {% include 'workflow/manager_log/order.html' %}
{% endfor %}

{% if page_obj.has_next and orders|length >= 50 %}
  {% include 'components/infinite_pagination.html' with page_obj=page_obj %}
{% endif %}