src/apps/workflow/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (OrderListView, OrderCreateView, OrderUpdateView, OrderDetailView,
                    NoteListView, ModelListView, ModelUpdateView, add_model, start_job,
                    start_second_stage, cancel_job, switch_job, add_note, add_delivery_job)


app_name = 'workflow'


urlpatterns = [
    path('', TemplateView.as_view(template_name='main/home.html'), name='home'),

    path('orders/', OrderListView.as_view(), name='orders-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<slug:slug>/', OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>/update', OrderUpdateView.as_view(), name='order-update'),
    path('orders/add', OrderCreateView.as_view(), name='order-add'),

    path('orders/<int:pk>/notes', NoteListView.as_view(), name='order-notes'),
    path('orders/<int:order_id>/notes/add', add_note, name='note-create'),

    path('orders/start_job/<int:order_id>', start_job, name='start-job'),
    path('orders/cancel_job/<int:order_id>', cancel_job, name='cancel-job'),
    path('orders/start_second_stage/<int:order_id>', start_second_stage, name='start-second-stage'),
    path('orders/switch_job/<int:order_id>/<slug:slug>/<int:stage_id>', switch_job, name='switch-job'),
    path('orders/add_delivery_job/<int:order_id>', add_delivery_job, name='add-delivery-job'),


    path('models/', ModelListView.as_view(), name='models'),
    path('models/add', add_model, name='model-add'),
    path('models/<int:pk>/update', ModelUpdateView.as_view(), name='model-update'),
]

src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('tinymce/', include('tinymce.urls')),

    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('accounts/password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             success_url='/login/'
         ),
         name='password_reset'),
    path('accounte/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    path('', include('workflow.urls', namespace='workflow'), name='home'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/apps/workflow/models/base.py
from django.db import models


class BaseModel(models.Model):

    id = models.AutoField(primary_key=True)

    class Meta:
        abstract = True



class Nameable(models.Model):

    name = models.CharField(max_length=100)

    class Meta:
        abstract = True



class Creatable(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True



class Updatable(models.Model):

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

src/apps/workflow/models/stage.py
from django.db import models

from .base import BaseModel, Nameable

class WfStageList(BaseModel, Nameable):

    DEFAULT_STAGE_ID = 2

    class Meta:
        managed = False
        db_table = 'wf_stage_list'


    def __str__(self):
        return self.name



class WfWorkStageList(BaseModel, Nameable):

    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(unique=True)

    DEFAULT_STAGE_ID = 1

    class Meta:
        managed = False
        db_table = 'wf_work_stage_list'

        verbose_name = 'Стадію виконання роботи'
        verbose_name_plural = 'Стадії виконання роботи'


    def __str__(self):
        return self.name



class OrderStatusList(BaseModel, Nameable):

    DEFAULT_STATUS_ID = 1

    class Meta:
        managed = False
        db_table = 'wf_order_status_list'

        verbose_name = 'Статус замовлення'
        verbose_name_plural = 'Статуси замовлень'


    def __str__(self):
        return self.name

src/apps/workflow/views.py
import json

from django.db.models import Q, OuterRef, Subquery, Value, Max, F, Count, Prefetch, Case, When, Exists, BooleanField
from django.db.models.lookups import GreaterThan
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from django.views.decorators.http import require_http_methods
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, Http404
from django.core.exceptions import ObjectDoesNotExist

from .models.core import Order, OrderStatus, OrderWorkStage, WorkLog, Note, WfModelList, WfWorkStageList
from .models.stage import WfStageList, OrderStatusList
from .filters import OrderFilter, NoteFilter
from .forms import OrderForm, NoteLogForm, ModelForm
from .mixins import FilteredListViewMixin
from .pagination import CustomPagination
from .queries import get_max_work_stages, get_current_stage
from .utils import annotate_current_stage, annotate_notes


class OrderListView(LoginRequiredMixin, FilteredListViewMixin):

    http_method_names = ['get', 'head', 'options', 'trace',]

    queryset = Order.objects.all()
    ordering = ['-id',]
    paginate_by = 50
    paginator_class = CustomPagination
    filterset_class = OrderFilter

    context_object_name = 'orders'
    template_name = 'workflow/order/list.html'


    def get_queryset(self):
        queryset = super().get_queryset()

        principal_groups = self.kwargs.get('principal_groups', [])

        select_related = [
            'model',
            'configuration',
            'fireclay_type',
            'glazing_type',
            'handle_type',
            'frame_type',
            'priority',
        ]

        prefetch_related = []

        work_stages = get_max_work_stages()

        queryset = queryset.annotate(**annotate_current_stage(work_stages))

        if any(x in ['manager', 'lead', ] for x in principal_groups):
            select_related += ['payment']

            ready_for_second_stage = OrderWorkStage.objects.raw(
                '''
                    SELECT wol.id FROM wf_order_log wol
                    WHERE wol.start_manufacturing_semi_finished  = 0 AND
                    wol.id IN (
                        SELECT wows.order_id FROM wf_order_work_stage wows
                        INNER JOIN wf_work_log wwl
                        ON wows.id = wwl.order_work_stage_id
                        WHERE wows.work_stage_id <= 6
                        AND wows.order_id IN (
                            SELECT wows.order_id  FROM wf_order_work_stage wows
                            INNER JOIN wf_work_log wwl
                            ON wows.id = wwl.order_work_stage_id
                            WHERE wows.work_stage_id > 6
                            GROUP BY wows.order_id
                            HAVING COUNT(DISTINCT wows.id) = SUM(CASE WHEN wwl.stage_id = 1 THEN 0 ELSE 1 END)
                        )
                        GROUP BY wows.order_id
                        HAVING COUNT(DISTINCT wows.id) = SUM(CASE WHEN wwl.stage_id = 1 THEN 1 ELSE 0 END)
                    );
                '''
            )

            orders_ = Order.objects.filter(Q(id__in=OuterRef('id')) & Q(id__in=[id.id for id in ready_for_second_stage])) \
                                   .annotate(ready_for_second_stage=Value(True))

            max_status_ = OrderStatus.objects.values('order').annotate(max_id=Max('id'))
            is_ready = OrderStatus.objects.filter(
                id__in=Subquery(max_status_.values('max_id')),
                order=OuterRef('id'),
                status=2
            )
            is_not_cancellable = OrderStatus.objects.filter(
                id__in=Subquery(max_status_.values('max_id')),
                order=OuterRef('id'),
                status_id__in=[3, 4]
            )

            work_log_ = WorkLog.objects.values('work_stage__order').annotate(max_id=Max('id'))
            work_log = WorkLog.objects.filter(
                Q(work_stage__order=OuterRef('id')) &
                Q(id__in=Subquery(work_log_.values('max_id'))),
            )

            queryset = queryset.annotate(
                notes_count=Count('notes', distinct=True),
                ready_for_second_stage=Subquery(orders_.values('ready_for_second_stage')),
                ready_for_delivery=Case(
                        When(
                            Exists(is_ready) & ~Exists(OrderWorkStage.objects.filter(Q(order=OuterRef('id')) & Q(stage__id=12))),
                            then=Value(True)
                            ),
                        default=Value(False),
                        output_field=BooleanField()
                    ),
                is_cancellable=Case(
                        When(
                            Exists(is_not_cancellable),
                            then=Value(False)
                            ),
                        default=Value(True),
                        output_field=BooleanField()
                ),
                stage_status=Subquery(work_log.values('stage')),
            )

        else:
            slug = self.kwargs.get('slug', None)
            listing = self.request.GET.get('listing', 'in_progress')

            try:
                stage = WfWorkStageList.objects.get(slug=slug)
            except ObjectDoesNotExist:
                raise Http404

            prefetch_related += ['notes',]

            # work_log_ = WorkLog.objects.raw(
            #     '''
            #         SELECT wwl.id
            #         FROM wf_work_log wwl
            #         INNER JOIN  (
            #             SELECT MAX(wwl_.id) AS max_id
            #             FROM wf_work_log wwl_
            #             INNER JOIN wf_order_work_stage wows_ ON wwl_.order_work_stage_id = wows_.id
            #             WHERE wows_.work_stage_id = %s
            #             GROUP BY wwl_.order_work_stage_id
            #         ) temp_
            #         ON temp_.max_id = wwl.id;
            #     ''', [stage.id]
            # )

            # work_log = WorkLog.objects.filter(
            #     Q(work_stage__order=OuterRef('id')) &
            #     Q(id__in=[id.id for id in work_log_])
            # )

            work_log_ = WorkLog.objects.values('work_stage').filter(
                            Q(work_stage__stage=stage)
                        ).annotate(max_id=Max('id'))

            work_log = WorkLog.objects.filter(
                Q(work_stage__order=OuterRef('id')) &
                Q(id__in=Subquery(work_log_.values('max_id')))
            )

            work_stage_last = OrderWorkStage.objects.values('order').filter(
                Q(order_of_execution__in=Subquery(
                    OrderWorkStage.objects.filter(Q(order=OuterRef('order')) & Q(stage=stage) & Q(is_locked=False)).values('order_of_execution')) - 1
                  ) &
                Q(order=OuterRef('id')) &
                Q(logs__stage__isnull=False)
            ).annotate(last_date=Max('logs__created_at'))


            max_status_ = OrderStatus.objects.values('order').annotate(max_id=Max('id'))
            is_delivered_or_cancelled = OrderStatus.objects.filter(Q(id__in=max_status_.values('max_id')) & Q(order__id=OuterRef('id')) & Q(status__in=[3, 4]))

            listing_filter = Q()
            if listing == 'in_progress' and 'employee' in principal_groups:
                listing_filter = (
                    # Q(order_stages__logs__in=Subquery(work_log_.values('max_id'))) &
                    ~Q(order_stages__logs__stage__id=1)
                )


            queryset = queryset.filter(
                                    Q(order_stages__stage=stage) &
                                    Q(order_stages__is_locked=False) &
                                    Q(start_manufacturing_semi_finished=Case(
                                            When(order_stages__stage__gt=6, then=True),
                                            default=F('start_manufacturing_semi_finished')
                                        )
                                    ) &
                                    Q(listing_filter) &
                                    ~Q(statuses__in=Subquery(is_delivered_or_cancelled.values('id')))
                                ) \
                                .annotate(
                                    notes_count=Count('notes', distinct=True),
                                    username=work_log.values('user__username'),
                                    stage_id=work_log.values('stage__id'),
                                    work_completed_date=Case(
                                        When(GreaterThan(F('order_stages__order_of_execution'), 0),
                                        then=Subquery(work_stage_last.values('last_date'))),
                                        default=F('start_date')
                                    )
                                )

        queryset = queryset.select_related(*select_related).prefetch_related(*prefetch_related)

        return queryset


    def get_template_names(self):
        template = super().get_template_names()
        is_partial = self.request.headers.get('HX-Trigger', None) == 'paginator'

        principal_groups = self.kwargs.get('principal_groups', [])
        work_groups = self.kwargs.get('work_groups', [])

        template_map = {
            'dxf_version_control': 'workflow/dxf_log',
            'cut': 'workflow/cut_log',
            'bend': 'workflow/bend_log',
            'weld': 'workflow/weld_log',
            'locksmith': 'workflow/locksmith_log',
            'locksmith_door': 'workflow/locksmith_log',
            'paint': 'workflow/paint_log',
            'fireclay': 'workflow/fireclay_log',
            'glass': 'workflow/glass_log',

src/apps/workflow/templates/workflow/model/add.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'workflow:home' %}" class="">
            <span class="flex items-center mdi p-0.5 md:p-1 mdi-chevron-right text-gray-700 hover:text-gray-900">
                <span class="ml-2">Головна</span>
            </span>
        </a>
    </li>
    <li>
        <a href="{% url 'workflow:orders' %}" class="">
            <span class="flex items-center mdi p-0.5 md:p-1 mdi-chevron-right text-gray-700 hover:text-gray-900">
                <span class="ml-1">замовлення</span>
            </span>
        </a>
    </li>
{% endblock %}

{% block content %}
    <div class="bg-slate-300 shadow-md rounded-sm mx-2 sm:mx-auto p-5 mt-10 max-w-2xl justify-center text-sm md:text-base">
        <h1 class="p-2 text-center font-medium">Додати нову модель</h1>
        <div class="flex justify-center gap-2 md:gap-4 px-10 md:px-5 mt-2">

            <form method="post" class="space-y-1 md:space-y-2 space-x-2">
                {% csrf_token %}

                {% for field in form %}
                    <div class="grid grid-cols-1 md:grid-cols-2">
                        <div class="">
                            <div class="block mb-2 text-sm font-medium text-gray-900">
                                {{ field.label_tag }}
                            </div>
                            {% if field.help_text %}
                                <sup>{{ field.help_text }}</sup>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="">
                                    <div class="text-red-900">{{error}}</div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="flex flex-row">
                            {{ field }}
                        </div>
                     </div>
                {% endfor %}

                <div class="flex justify-center">
                    <button type="submit"
                            class="mt-2 items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            Створити
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

src/apps/workflow/templates/workflow/model/create.html
<form hx-post="{% url 'workflow:model-add' %}" id="model-form">
    {% csrf_token %}
    <label for="{{ form.name.id_for_label }}" class="text-sm sm:text-base">Нова модель</label>
    <textarea name="name"
              rows="1"
              required="" 
              id="id_name" 
              spellcheck="false"
              class="block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
    </textarea>
    <div class="text-red-500 font-semibold">
        {{ form.name.errors }}
    </div>
    <div class="flex justify-end">
        {% include 'components/buttons/add.html' %}
    </div>
</form>

src/apps/workflow/templates/workflow/model/list.html
{% extends "base.html" %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'workflow:home' %}" class="">
            <span class="flex items-center mdi p-0.5 md:p-1 mdi-chevron-right text-gray-700 hover:text-gray-900">
                <span class="ml-2">Головна</span>
            </span>
        </a>
    </li>
    <li>
        <a href="{% url 'workflow:orders' %}" class="">
            <span class="flex items-center mdi p-0.5 md:p-1 mdi-chevron-right text-gray-700 hover:text-gray-900">
                <span class="ml-1">замовлення</span>
            </span>
        </a>
    </li>
{% endblock %}

{% block content %}
    <div class="max-w-2xl mt-2 mx-auto pb-20" id="models-list" hx-swap-oob="true">
        <h1 class="text-base sm:text-lg text-center font-bold mb-2">Моделі топок</h1>
        <div class="bg-white shadow-md text-sm sm:text-base rounded-sm mx-2 p-2 sm:p-5 h-2/3">
            <div class="flex mb-3"
                 hx-get="{% url 'workflow:models' %}"
                 hx-swap="innerHTML"
                 hx-target="#models-list"
                 hx-trigger="modelsListChanged from:#model-form">
                <ul class="space-y-1 sm:space-y-2">
                    {% for model in models %}
                        <li>
                            <a href="{% url 'workflow:model-update' model.id %}">
                                <span class="px-3 text-blue-700 whitespace-nowrap">{{ model.id }}</span>
                            </a>
                            <span>{{ model.name }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {% include 'workflow/model/create.html' %}
        </div>
    </div>
{% endblock %}

src/apps/workflow/templates/workflow/model/update.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'workflow:home' %}" class="">
            <span class="flex items-center mdi p-0.5 md:p-1 mdi-chevron-right text-gray-700 hover:text-gray-900">
                <span class="ml-2">Головна</span>
            </span>
        </a>
    </li>
    <li>
        <a href="{% url 'workflow:orders' %}" class="">
            <span class="flex items-center mdi p-0.5 md:p-1 mdi-chevron-right text-gray-700 hover:text-gray-900">
                <span class="ml-1">замовлення</span>
            </span>
        </a>
    </li>
{% endblock %}

{% block content %}
    <div class="bg-slate-300 shadow-md rounded-sm mx-2 sm:mx-auto p-5 mt-10 max-w-2xl justify-center text-sm md:text-base">
        <h1 class="p-2 text-center font-medium">Редагувати модель</h1>
        <div class="flex justify-center gap-2 md:gap-4 px-10 md:px-5 mt-2">

            <form method="post" class="space-y-1 md:space-y-2 space-x-2">
                {% csrf_token %}

                {% for field in form %}
                    <div class="grid grid-cols-1 md:grid-cols-2">
                        <div class="">
                            <div class="block mb-2 text-sm font-medium text-gray-900">
                                {{ field.label_tag }}
                            </div>
                            {% if field.help_text %}
                                <sup>{{ field.help_text }}</sup>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="">
                                    <div class="text-red-900">{{error}}</div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="flex flex-row">
                            {{ field }}
                        </div>
                     </div>
              {% endfor %}

                <div class="flex justify-center">
                    <button type="submit"
                            class="mt-2 items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            Зберегти
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}